name: Terraform Lint & Validate

on:
  push:
  pull_request:

jobs:
  terraform:
    name: Format & Validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: terraform fmt (check)
        run: terraform fmt -check -diff -recursive

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate
